language: emacs-lisp
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # Update and install the Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_script:
  - make EMACS=${EMACS} elpa
script:
  - make EMACS=${EMACS} test
